Repository lugorguk/lug.org.uk-website, pull requests merged in 2019-04, with the labels that each got.

#86 Delete 0000-01-01-North-West London.md
  _posts/0000-01-01-North-West London.md
Labels: LUG Deletion

#88 Add Ayrshire LUG
  _posts/0000-01-01-Ayrshire.md
Labels: New/Changed LUG

#98 Delete 0000-01-01-North of Scotland.md
  _posts/0000-01-01-North of Scotland.md
Labels: Issue With URL, LUG Deletion

#91 Delete 0000-01-01-Leigh.md
  _posts/0000-01-01-Leigh.md
Labels: LUG Deletion

#95 Delete 0000-01-01-East Hertfordshire.md
  _posts/0000-01-01-East Hertfordshire.md
Labels: Issue With URL, LUG Deletion

#94 Update 0000-01-01-East Grinstead.md
  _posts/0000-01-01-East Grinstead.md
Labels: Issue With URL, New/Changed LUG

#96 Delete 0000-01-01-Bassetlaw.md
  _posts/0000-01-01-Bassetlaw.md
Labels: LUG Deletion

#97 Delete 0000-01-01-B-lux.md
  _posts/0000-01-01-B-lux.md
Labels: Issue With URL, LUG Deletion

#99 Delete 0000-01-01-Swindon.md
  _posts/0000-01-01-Swindon.md
Labels: Issue With URL, LUG Deletion

#106 Removes S from HTTPS in Ayrshire LUG website
  _posts/0000-01-01-Ayrshire.md
Labels: Issue With URL

#105 Delete Glastonbury LUG - Fixes #102
  _posts/0000-01-01-Glastonbury.md
Labels: Issue With URL, LUG Deletion

#109 Update 0000-01-01-Falkirk.md
  _posts/0000-01-01-Falkirk.md
Labels: Issue With URL

#110 Delete 0000-01-01-Dundee & Tayside.md
  _posts/0000-01-01-Dundee & Tayside.md
Labels: Issue With URL, LUG Deletion
